import './globals.css'
import Navbar from './component/navbar/navbar'
import { Nunito } from "next/font/google"
import ClientOnly from './clientOnly'

export const metadata = {
  title: 'Asspects in life',
  description: 'Generated by joe and mendy',
}

const font = Nunito({subsets: ["latin"]})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <Navbar />
          <div style={{marginTop: 64}}>
            {children}
            </div>
          </ClientOnly>
      </body>
    </html>
  )
}
